apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxypool-okteto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxypool-okteto
  template:
    metadata:
      labels:
        app: proxypool-okteto
    spec:
      containers:
      - name: proxypool-okteto
        image: okteto.dev/proxypoolnew:latest
        env:
        - name: CONFIG_FILE
          value: "https://raw.githubusercontent.com/daywincs/proxypoolnew/master/config/config.yaml"
        - name: DOMAIN
          value: "proxypool-okteto-daywincs.cloud.okteto.net"
        ports:
        - containerPort: 12580
